<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <#include script src="https://cdn.tailwindcss.com"></script>

    </head>
    <body>
        <div class="container">
            <p>Dear ${firstName} ${lastName},</p>
            <p>Sending Email using Spring 4 with <b>FreeMarker template !!!</b></p>
            <p>Thanks</p>
            <a href="http://localhost:4200">Click here</a>
        </div>
    </body>
</html>