<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

    </head>
    <div style="background-color: gray; color: green">
        <p>Dear ${firstName} ${lastName},</p>
        <p>Sending Email using Spring 4 with <b>FreeMarker template !!!</b></p>
        <p>Thanks</p>
        <a href="http://localhost:4200">Click here</a>
    </div>
</html>