<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

    </head>
    <body>
        <div>
            <h1>Hello ${name}</h1>
            <h1>Welcome in the best todo list app in world</h1>
            <p>
                Your credentials:<br>
                Login: ${login}<br>
                Password: ${password}
            </p>
            <p><a href="http://localhost:4200/lists">Click</a> to go to app.</p>

        </div>
    </body>
</html>